app/views/layouts/application.html.erb
=> コンフリクトを起こしてみよう

app/views/layouts/application.html.erb
=> [Add]views追加

Gemfile, Gemfile.lock, config/environments/development.rb, package.json, yarn.lock
複数選択ができるように列挙型enumをGemfileに追加しました。
=> [Add]enum追加

config/application.rb
追記ミスすみません。
改めて
①Gemfile
②enum日本語対応
追加しました。
二宮
=> [Add]Gemfile追記　enum日本語対応化

config/locales/ja.yml, config/routes.rb, db/migrate/20230715115639_devise_create_customers.rb
=> [Add] ja.yml

app/assets/stylesheets/public/homes.scss, app/controllers/public/confirmations_controller.rb, app/controllers/public/homes_controller.rb, app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/helpers/public/homes_helper.rb, config/routes.rb, test/controllers/public/homes_controller_test.rb
=> [Add] homes#top

app/models/item.rb, app/models/order.rb, app/models/order_detail.rb
アソシエーション追加のため以下のモデルに追記しました
items　テーブル
has_many :order_details, class_name: "OrderDetail",foreign_key: "item_id", dependent: :destroy
has_many :orders, through: :order_details
order_details　テーブル
belongs_to :items
belongs_to :orders
orders　　テーブル
has_many :order_details, class_name: "OrderDetail",foreign_key: "order_id", dependent: :destroy
has_many :items, through: :order_details
=> [Add]商品と注文のアソシエーション追加

app/javascript/packs/application.js, app/javascript/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb, app/views/public/shared/_links.html.erb, config/webpack/environment.js, package.json, yarn.lock
=> [Delete] Bootstrap

Gemfile, Gemfile.lock, app/controllers/admin/homes_controller.rb, app/controllers/admin/sessions_controller.rb, app/javascript/packs/application.js, app/views/admin/homes/top.html.erb, config/routes.rb, config/webpack/environment.js, db/seeds.rb
adminのログイン機能を追加しました。
bootstrapを導入しました。
=> adminログイン機能とbootstrap

app/assets/stylesheets/admin/orders.scss, app/controllers/admin/orders_controller.rb, app/helpers/admin/orders_helper.rb, app/javascript/stylesheets/application.scss, app/models/order.rb, app/models/order_detail.rb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb, config/application.rb, config/locales/ja.yml, test/controllers/admin/orders_controller_test.rb
作成したもの
oderモデル：注文ステータス、支払い方法の作成
order_detailモデル：制作ステータスの作成
=> 注文ステータス、制作ステータスの作成、支払い方法の作成

config/routes.rb
・public/customersコントローラのshow, edit, updateアクションのURLを:id => information に変更
・public/cart_itemsコントローラのupdateアクションのHTTPメソッドをPUT => PATCH に変更
=> [Refactor] customers/informationのurlを変更

app/controllers/admin/orders_controller.rb, app/models/order.rb, app/models/order_detail.rb, config/locales/ja.yml
=> コメントアウトを追加しました

app/controllers/admin/items_controller.rb, app/models/item.rb, app/views/admin/orders/show.html.erb, config/locales/ja.yml, config/routes.rb
・indexアクションの作成
・showアクションの作成
・newアクションの作成
・createアクションの作成
・updateアクションの作成
・editアクションの作成
=> itemコントローラーの作成

app/controllers/admin/items_controller.rb, app/models/item.rb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb
・商品一覧ページの作成
・新規登録機能の作成
・新規登録可能
=> 商品一覧と新規登録機能の作成

app/controllers/admin/items_controller.rb, app/controllers/public/cart_items_controller.rb, app/controllers/public/items_controller.rb, app/models/application_record.rb, app/models/item.rb, app/views/public/cart_items/index.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb
=> [Add] 顧客商品一覧・詳細

app/controllers/public/addresses_controller.rb, app/models/customer.rb, app/views/public/addresses/_form.html.erb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb, db/schema.rb
=> [Add]配送先新規登録部分テンプレート作成

Gemfile, Gemfile.lock, app/controllers/admin/items_controller.rb, app/controllers/admin/orders_controller.rb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/show.html.erb, app/views/admin/orders/show.html.erb, db/schema.rb
=> itemのshowとeditページの作成

Gemfile, app/controllers/admin/items_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/items_controller.rb, app/models/genre.rb, app/models/order.rb, app/views/admin/items/show.html.erb, app/views/public/customers/show.html.erb, app/views/public/items/index.html.erb, config/routes.rb
マイページのルーディングと、商品（顧客）のコントローラを編集しました
=> [Fix] customers routes

app/views/layouts/_header.html.erb, app/views/public/items/show.html.erb
=> [Fix] 顧客商品一覧、詳細

Gemfile, Gemfile.lock, app/controllers/public/cart_items_controller.rb, app/controllers/public/customers_controller.rb, app/models/cart_item.rb, app/views/public/cart_items/index.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, config/routes.rb
カートアイテムの「カートを空にする」と「合計金額」のエラーを解消し、カート機能が完成しました。
=> Feature/cart items/public

app/controllers/public/customers_controller.rb, app/models/customer.rb, app/views/public/cart_items/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, config/routes.rb
=> [Add] mypage

app/views/public/cart_items/index.html.erb
cart_items/index.htmlのコンフリクトの解消を行いました
=> [fix] cart_items/index.htmlのコンフリクト解消

app/controllers/public/cart_items_controller.rb, app/views/public/cart_items/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, config/routes.rb
public/customers/edit.htmlのform_withにhttpメソッドを定義、 urlを customers_information_pathに変更しました。
=> [Fix] public/customers/editのエラー修正

app/controllers/public/customers_controller.rb, app/models/customer.rb, app/views/public/cart_items/index.html.erb, app/views/public/customers/confirm_withdraw.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/orders/confirm.html.erb
=> [Add] 退会機能

app/controllers/admin/customers_controller.rb, app/controllers/public/registrations_controller.rb, app/models/genre.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/items/_form.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/new.html.erb, app/views/layouts/_header.html.erb, app/views/public/orders/confirm.html.erb, app/views/public/registrations/new.html.erb, config/routes.rb
=> 会員一覧の詳細ページと編集ページの作成

app/assets/stylesheets/public/genres.scss, app/controllers/public/genres_controller.rb, app/controllers/public/homes_controller.rb, app/helpers/public/genres_helper.rb, app/views/public/genres/_search_sidebar.html.erb, app/views/public/genres/show.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, config/routes.rb, test/controllers/public/genres_controller_test.rb
ジャンルサイドバー（部分テンプレート）とその呼び出し（顧客のトップ、商品一覧、商品詳細）を記述しました。
ジャンル検索結果表示のページ（show)を作成しました
=> [Add] genre/search_sidebar

app/controllers/admin/customers_controller.rb, app/models/customer.rb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
=> バリデーションの設定

app/models/customer.rb, app/views/public/genres/_search_sidebar.html.erb, app/views/public/genres/show.html.erb, app/views/public/items/show.html.erb, config/routes.rb
genres/show.html.erbのコードの整理を行いました
=> [Update] genres-layout

app/views/public/orders/confirm.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/show.html.erb
=> [Add]注文情報詳細

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/assets/stylesheets/public/genres.scss, app/models/item.rb, app/views/public/cart_items/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/genres/_search_sidebar.html.erb, app/views/public/genres/show.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, db/schema.rb
items/show,indexの価格を税込価格に訂正しました。
ジャンルサイドバー、カートアイテム、マイページのレイアウトを調整しました。
=> [Fix] genre,cart_item,item

app/views/layouts/application.html.erb, config/locales/devise.ja.yml
=> [Add] devise.ja.ymlに追加

app/controllers/public/cart_items_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/orders_controller.rb, app/views/layouts/application.html.erb, app/views/public/cart_items/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/items/show.html.erb
=> [Fix] customers/information/edit

app/controllers/public/items_controller.rb, app/views/public/items/index.html.erb
=> [Add] 顧客商品一覧のページネーション

app/controllers/public/customers_controller.rb, app/controllers/public/sessions_controller.rb, app/models/customer.rb, config/locales/devise.ja.yml
=> [Fix]　　退会後のログインについて　
